# Generated by Django 5.1.6 on 2025-03-27 21:15

from django.db import migrations


def update_site_name(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    site = Site.objects.get(id=1)
    site.name = 'Titan Clothing'
    site.domain = 'titan-clothing-app-9a3af2f08286.herokuapp.com'
    site.save()


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(update_site_name),
    ]
