# Generated by Django 5.1.6 on 2025-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(blank=True, help_text='Category group for navigation menu', max_length=254, null=True),
        ),
    ]
